[build-system]
requires = [ "flit_core >=3.2,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "jupyter_echarts"
version = "0.1.10"
authors = []
classifiers = [ "License :: OSI Approved :: MIT License",]
dynamic = [ "description",]

[project.license]
file = "LICENSE"
